agents:
  text_processor:
    description: "General text processing and analysis agent using Kimi K2"
    model_type: "kimi"
    api_key: ""  # Add your Kimi API key here
    api_endpoint: ""  # Optional: custom endpoint
    max_tokens: 1500
    temperature: 0.7
    timeout: 30
    retry_attempts: 3
    custom_params:
      top_p: 0.9
      frequency_penalty: 0.0
      presence_penalty: 0.0

  code_analyzer:
    description: "Code analysis and documentation agent using Qwen3"
    model_type: "qwen"
    api_key: ""  # Add your Qwen API key here
    api_endpoint: ""  # Optional: custom endpoint
    max_tokens: 2000
    temperature: 0.3
    timeout: 45
    retry_attempts: 3
    custom_params:
      top_p: 0.8
      repetition_penalty: 1.1

  research_agent:
    description: "Information gathering and synthesis agent using Kimi K2"
    model_type: "kimi"
    api_key: ""  # Add your Kimi API key here
    api_endpoint: ""  # Optional: custom endpoint
    max_tokens: 2500
    temperature: 0.8
    timeout: 60
    retry_attempts: 3
    custom_params:
      top_p: 0.95
      frequency_penalty: 0.1